name: Create Release Assets

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get version from release
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Read CHANGELOG.md
        id: changelog
        run: |
          CHANGELOG=$(cat CHANGELOG.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - name: Create ZIP with LF line endings
        run: |
          git config --global core.autocrlf input
          git config --global core.eol lf
    
          # Create a temp directory for the archive
          mkdir -p temp_archive
    
          # Copy files to temp directory with LF endings, excluding specified files
          git ls-files | grep -v "README.md\|CHANGELOG.md\|.gitattributes\|.github/" | while read file; do
            if [ -f "$file" ]; then
              mkdir -p "temp_archive/$(dirname "$file")"
              cat "$file" | tr -d '\r' > "temp_archive/$file"
            fi
          done
    
          # Create the ZIP archive
          cd temp_archive
          zip -r ../LimitlessPhotos.zip .
          cd ..
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: v${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          files: LimitlessPhotos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}