name: Create Release Archive

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Read changelog for release notes
      - name: Read changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./CHANGELOG.md

      # Update GitHub Release description
      - name: Update Release Description
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Install 7zip
      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      # Create archive using 7zip with store-only mode
      - name: Archive Release with 7zip
        run: |
          7z a -tzip -mx0 LimitlessPhotos.zip ./* \
            -xr!.git -xr!.github -xr!node_modules -x!.editorconfig -x!README.md -x!CHANGELOG.md

      # Upload zip file to release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./LimitlessPhotos.zip
          asset_name: LimitlessPhotos.zip
          asset_content_type: application/zip